"use client";
import { useEffect, useMemo, useState } from "react";
import { Plus, Search, Users, Trash2 } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";

export default function CustomersPage() { const [customers,setCustomers]=useState<any[]>([]); const [q,setQ]=useState(""); const [open,setOpen]=useState(false); const [form,setForm]=useState({customerName:"",mobile:"",email:"",gstNumber:"",address:""}); const [busy,setBusy]=useState(false);
  async function load(){ const r=await fetch(`/api/customers?q=${encodeURIComponent(q)}`); const d=await r.json(); setCustomers(d.data||[]); } useEffect(()=>{load()},[q]);
  async function create(){ setBusy(true); const r=await fetch("/api/customers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const d=await r.json(); setBusy(false); if(!r.ok) return alert(typeof d.error === "string" ? d.error : "Could not create customer"); setOpen(false); setForm({customerName:"",mobile:"",email:"",gstNumber:"",address:""}); load(); }
  async function remove(id:string){ if(!confirm("Delete this customer? Customers with invoices cannot be deleted.")) return; const r=await fetch(`/api/customers/${id}`,{method:"DELETE"}); const d=await r.json(); if(!r.ok) return alert(d.error||"Cannot delete"); load(); }
  return <AppShell><div className="mx-auto max-w-[1500px] p-5 md:p-8"><PageHeader title="Customers" description="Manage buyers, contacts, and receivable relationships." action={<Button onClick={()=>setOpen(true)}><Plus size={16}/>Add customer</Button>}/><div className="card overflow-hidden"><div className="border-b p-4"><div className="relative max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input className="field pl-10" placeholder="Search customer, phone or email" value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-6 py-3">Customer</th><th className="px-6 py-3">Phone</th><th className="px-6 py-3">Email</th><th className="px-6 py-3">Invoices</th><th className="px-6 py-3 text-right">Action</th></tr></thead><tbody>{customers.map(c=><tr key={c.id} className="border-b last:border-0"><td className="px-6 py-4"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-indigo-50 text-brand"><Users size={17}/></div><div><p className="font-semibold">{c.customerName}</p><p className="text-xs text-slate-400">{c.gstNumber || "No GSTIN"}</p></div></div></td><td className="px-6 py-4">{c.mobile}</td><td className="px-6 py-4 text-slate-500">{c.email || "—"}</td><td className="px-6 py-4">{c._count?.invoices ?? 0}</td><td className="px-6 py-4 text-right"><button className="rounded-lg p-2 text-rose-500 hover:bg-rose-50" onClick={()=>remove(c.id)}><Trash2 size={16}/></button></td></tr>)}</tbody></table>{!customers.length&&<div className="p-10 text-center text-sm text-slate-500">No customers found.</div>}</div></div></div>{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-bold">Add customer</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["customerName","Customer name"],["mobile","Mobile"],["email","Email"],["gstNumber","GSTIN"]].map(([k,l])=><label key={k} className="block"><span className="mb-2 block text-sm font-semibold">{l}</span><input className="field" value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="block sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Address</span><textarea className="field min-h-24" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label></div><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={busy} onClick={create}>{busy?"Saving…":"Save customer"}</Button></div></div></div>}</AppShell> }
