"use client";
import { ArrowDownRight, ArrowUpRight, CalendarDays, ChevronRight, Clock3, FileWarning, MessageCircle, Phone, Send, TrendingUp } from "lucide-react";
import { useEffect, useState } from "react";
import { CollectionChart } from "@/components/collection-chart";
import { Button } from "@/components/ui/button";
import { cn, formatINR } from "@/lib/utils";

const statusClasses: Record<string,string> = { OVERDUE: "bg-rose-50 text-rose-600", DUE: "bg-amber-50 text-amber-700", SENT: "bg-blue-50 text-blue-600", PARTIALLY_PAID: "bg-violet-50 text-violet-600", PAID: "bg-emerald-50 text-emerald-700", DRAFT: "bg-slate-100 text-slate-600" };
export function Dashboard() {
  const [data, setData] = useState<any>(null);
  useEffect(() => { fetch("/api/dashboard").then(r => r.json()).then(r => setData(r.data)); }, []);
  if (!data) return <div className="p-6"><div className="h-40 animate-pulse rounded-2xl bg-white"/></div>;
  const cards = [
    { label: "Total billed", value: formatINR(data.kpis.totalBilled), delta: `${data.recentInvoices.length} recent`, tone: "indigo", icon: TrendingUp },
    { label: "Pending amount", value: formatINR(data.kpis.pending), delta: "Needs collection", tone: "amber", icon: TrendingUp },
    { label: "Overdue amount", value: formatINR(data.kpis.overdue), delta: "Requires action", tone: "rose", icon: FileWarning },
    { label: "Paid this month", value: formatINR(data.kpis.paidThisMonth), delta: `${data.kpis.collectionRate.toFixed(1)}% overall rate`, tone: "emerald", icon: TrendingUp },
  ];
  return <div className="mx-auto max-w-[1500px] p-5 md:p-8"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-sm font-medium text-slate-500">Good morning, {data.company?.companyName || "team"}</p><h1 className="text-2xl font-bold tracking-tight md:text-3xl">Here&apos;s your collection snapshot.</h1></div><Button variant="secondary"><CalendarDays size={16}/>Live workspace</Button></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, delta, tone, icon: Icon }) => <div className="card p-5" key={label}><div className="flex justify-between"><p className="text-sm font-medium text-slate-500">{label}</p><span className={cn("grid size-9 place-items-center rounded-xl", tone === "indigo" && "bg-indigo-50 text-brand", tone === "amber" && "bg-amber-50 text-amber-600", tone === "rose" && "bg-rose-50 text-rose-500", tone === "emerald" && "bg-emerald-50 text-emerald-600")}><Icon size={18}/></span></div><p className="mt-3 text-2xl font-bold tracking-tight">{value}</p><p className={cn("mt-2 flex items-center gap-1 text-xs font-semibold", tone === "rose" ? "text-rose-500" : "text-emerald-600")}>{tone === "rose" ? <ArrowDownRight size={13}/> : <ArrowUpRight size={13}/>} {delta}</p></div>)}</section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.55fr_1fr]"><div className="card p-5 md:p-6"><div className="flex items-start justify-between"><div><h2 className="font-bold">Collection trend</h2><p className="mt-1 text-sm text-slate-500">Collected versus outstanding amounts</p></div><div className="hidden gap-3 text-xs sm:flex"><span className="flex items-center gap-1.5"><i className="size-2 rounded-full bg-brand"/>Collected</span><span className="flex items-center gap-1.5"><i className="size-2 rounded-full bg-amber-500"/>Due</span></div></div><CollectionChart trend={data.trend}/></div><div className="card p-5 md:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold">Follow-up activity</h2><p className="mt-1 text-sm text-slate-500">Latest delivery attempts</p></div><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-bold text-brand">{data.reminders.length} recent</span></div><div className="mt-5 space-y-3">{data.reminders.length ? data.reminders.map((r:any) => { const Icon = r.channel === "WHATSAPP" ? MessageCircle : r.channel === "EMAIL" ? Send : Phone; return <div key={r.id} className="flex items-center gap-3 rounded-xl border p-3"><div className="grid size-9 place-items-center rounded-lg bg-slate-100 text-slate-600"><Icon size={17}/></div><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{r.channel} reminder</p><p className="truncate text-xs text-slate-500">{r.invoice.invoiceNumber} · {r.invoice.customer.customerName}</p></div><span className="text-xs font-bold text-slate-500">{r.status}</span></div>}) : <div className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No reminders yet.</div>}</div><a href="/collections" className="mt-4 block text-sm font-semibold text-brand">View collection activity <ChevronRight className="inline" size={14}/></a></div></section>
    <section className="card mt-5 overflow-hidden"><div className="flex items-center justify-between p-5 md:p-6"><div><h2 className="font-bold">Recent invoices</h2><p className="mt-1 text-sm text-slate-500">Keep your cash flow moving</p></div><a href="/invoices" className="text-sm font-semibold text-brand">View all invoices</a></div><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-y bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-6 py-3">Invoice</th><th className="px-6 py-3">Customer</th><th className="px-6 py-3">Due date</th><th className="px-6 py-3 text-right">Outstanding</th><th className="px-6 py-3 text-right">Status</th></tr></thead><tbody>{data.recentInvoices.map((invoice:any) => <tr key={invoice.id} className="border-b last:border-0"><td className="px-6 py-4 font-semibold text-brand">{invoice.invoiceNumber}</td><td className="px-6 py-4 font-medium">{invoice.customer.customerName}</td><td className="px-6 py-4 text-slate-500"><span className="flex items-center gap-2"><Clock3 size={14}/>{new Date(invoice.dueDate).toLocaleDateString("en-IN")}</span></td><td className="px-6 py-4 text-right font-semibold">{formatINR(Number(invoice.dueAmount))}</td><td className="px-6 py-4 text-right"><span className={cn("rounded-full px-2.5 py-1 text-xs font-bold", statusClasses[invoice.status] || "bg-slate-100 text-slate-600")}>{invoice.status.replaceAll("_", " ")}</span></td></tr>)}</tbody></table></div></section>
  </div>
}
