"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { WalletCards, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function LoginPage() {
  const router = useRouter(); const [email, setEmail] = useState("owner@aroramills.in"); const [password, setPassword] = useState("Demo@123"); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function onSubmit(e: FormEvent) { e.preventDefault(); setLoading(true); setError(""); const response = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const data = await response.json(); setLoading(false); if (!response.ok) return setError(data.error || "Login failed"); router.push("/dashboard"); router.refresh(); }
  return <main className="grid min-h-screen bg-[#f7f8fc] lg:grid-cols-2"><section className="hidden bg-brand p-12 text-white lg:flex lg:flex-col lg:justify-between"><div><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-white/15"><WalletCards/></div><span className="text-xl font-bold">PayTrack AI</span></div><div className="mt-20 max-w-xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-indigo-200">Cash collection OS</p><h1 className="mt-4 text-5xl font-bold leading-tight">Turn overdue invoices into predictable cash flow.</h1><p className="mt-6 text-lg leading-8 text-indigo-100">Track receivables, automate follow-ups, send payment links, and see exactly what your team needs to collect next.</p></div></div><p className="text-sm text-indigo-200">Built for Indian B2B businesses • GST-friendly workflow • INR collection</p></section><section className="flex items-center justify-center p-6"><div className="w-full max-w-md"><div className="mb-10 lg:hidden"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-brand text-white"><WalletCards/></div><span className="text-xl font-bold">PayTrack AI</span></div></div><div className="card p-7 md:p-8"><p className="text-sm font-semibold text-brand">Welcome back</p><h2 className="mt-2 text-3xl font-bold tracking-tight">Sign in to your workspace</h2><p className="mt-2 text-sm text-slate-500">Use the seeded demo account or your own workspace credentials.</p><form onSubmit={onSubmit} className="mt-7 space-y-4"><label className="block"><span className="mb-2 block text-sm font-semibold">Email</span><input className="field" type="email" value={email} onChange={e => setEmail(e.target.value)} required/></label><label className="block"><span className="mb-2 block text-sm font-semibold">Password</span><input className="field" type="password" value={password} onChange={e => setPassword(e.target.value)} required/></label>{error && <div className="rounded-xl bg-rose-50 px-4 py-3 text-sm font-medium text-rose-600">{error}</div>}<Button type="submit" className="w-full" disabled={loading}>{loading ? "Signing in…" : <>Sign in <ArrowRight size={16}/></>}</Button></form><div className="mt-5 rounded-xl bg-slate-50 p-4 text-xs text-slate-500"><b>Demo:</b> owner@aroramills.in / Demo@123</div></div></div></section></main>
}
